/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionVariable : ActionVariable return value of the query API
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionVariable {
    /// the value of the variable
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<String>,
    /// the name of the variable
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// the owner to which the variable belongs
    #[serde(rename = "owner_id", skip_serializing_if = "Option::is_none")]
    pub owner_id: Option<i64>,
    /// the repository to which the variable belongs
    #[serde(rename = "repo_id", skip_serializing_if = "Option::is_none")]
    pub repo_id: Option<i64>,
}

impl ActionVariable {
    /// ActionVariable return value of the query API
    pub fn new() -> ActionVariable {
        ActionVariable {
            data: None,
            name: None,
            owner_id: None,
            repo_id: None,
        }
    }
}
