/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EditTagProtectionOption : EditTagProtectionOption options for editing a tag protection
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditTagProtectionOption {
    #[serde(rename = "name_pattern", skip_serializing_if = "Option::is_none")]
    pub name_pattern: Option<String>,
    #[serde(rename = "whitelist_teams", skip_serializing_if = "Option::is_none")]
    pub whitelist_teams: Option<Vec<String>>,
    #[serde(
        rename = "whitelist_usernames",
        skip_serializing_if = "Option::is_none"
    )]
    pub whitelist_usernames: Option<Vec<String>>,
}

impl EditTagProtectionOption {
    /// EditTagProtectionOption options for editing a tag protection
    pub fn new() -> EditTagProtectionOption {
        EditTagProtectionOption {
            name_pattern: None,
            whitelist_teams: None,
            whitelist_usernames: None,
        }
    }
}
