/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EditGitHookOption : EditGitHookOption options when modifying one Git hook
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditGitHookOption {
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
}

impl EditGitHookOption {
    /// EditGitHookOption options when modifying one Git hook
    pub fn new() -> EditGitHookOption {
        EditGitHookOption { content: None }
    }
}
