/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LicensesTemplateListEntry : LicensesListEntry is used for the API
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LicensesTemplateListEntry {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl LicensesTemplateListEntry {
    /// LicensesListEntry is used for the API
    pub fn new() -> LicensesTemplateListEntry {
        LicensesTemplateListEntry {
            key: None,
            name: None,
            url: None,
        }
    }
}
