/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListActionRunResponse : ListActionRunResponse return a list of ActionRun
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListActionRunResponse {
    #[serde(rename = "total_count", skip_serializing_if = "Option::is_none")]
    pub total_count: Option<i64>,
    #[serde(rename = "workflow_runs", skip_serializing_if = "Option::is_none")]
    pub workflow_runs: Option<Vec<models::ActionRun>>,
}

impl ListActionRunResponse {
    /// ListActionRunResponse return a list of ActionRun
    pub fn new() -> ListActionRunResponse {
        ListActionRunResponse {
            total_count: None,
            workflow_runs: None,
        }
    }
}
