/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NodeInfoUsageUsers : NodeInfoUsageUsers contains statistics about the users of this server
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeInfoUsageUsers {
    #[serde(rename = "activeHalfyear", skip_serializing_if = "Option::is_none")]
    pub active_halfyear: Option<i64>,
    #[serde(rename = "activeMonth", skip_serializing_if = "Option::is_none")]
    pub active_month: Option<i64>,
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i64>,
}

impl NodeInfoUsageUsers {
    /// NodeInfoUsageUsers contains statistics about the users of this server
    pub fn new() -> NodeInfoUsageUsers {
        NodeInfoUsageUsers {
            active_halfyear: None,
            active_month: None,
            total: None,
        }
    }
}
