/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QuotaUsedSizeGit : QuotaUsedSizeGit represents the size-based git (lfs) quota usage of a user
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuotaUsedSizeGit {
    /// Storage size of the user's Git LFS objects
    #[serde(rename = "LFS", skip_serializing_if = "Option::is_none")]
    pub lfs: Option<i64>,
}

impl QuotaUsedSizeGit {
    /// QuotaUsedSizeGit represents the size-based git (lfs) quota usage of a user
    pub fn new() -> QuotaUsedSizeGit {
        QuotaUsedSizeGit { lfs: None }
    }
}
