/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QuotaUsedSizeAssetsPackages : QuotaUsedSizeAssetsPackages represents the size-based package quota usage of a user
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuotaUsedSizeAssetsPackages {
    /// Storage suze used for the user's packages
    #[serde(rename = "all", skip_serializing_if = "Option::is_none")]
    pub all: Option<i64>,
}

impl QuotaUsedSizeAssetsPackages {
    /// QuotaUsedSizeAssetsPackages represents the size-based package quota usage of a user
    pub fn new() -> QuotaUsedSizeAssetsPackages {
        QuotaUsedSizeAssetsPackages { all: None }
    }
}
