/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RenameOrgOption : RenameOrgOption options when renaming an organization
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RenameOrgOption {
    /// New username for this org. This name cannot be in use yet by any other user.
    #[serde(rename = "new_name")]
    pub new_name: String,
}

impl RenameOrgOption {
    /// RenameOrgOption options when renaming an organization
    pub fn new(new_name: String) -> RenameOrgOption {
        RenameOrgOption { new_name }
    }
}
