/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SubmitPullReviewOptions : SubmitPullReviewOptions are options to submit a pending pull review
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitPullReviewOptions {
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    /// ReviewStateType review state type
    #[serde(rename = "event", skip_serializing_if = "Option::is_none")]
    pub event: Option<String>,
}

impl SubmitPullReviewOptions {
    /// SubmitPullReviewOptions are options to submit a pending pull review
    pub fn new() -> SubmitPullReviewOptions {
        SubmitPullReviewOptions {
            body: None,
            event: None,
        }
    }
}
