/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionRunJob : ActionRunJob represents a job of a run
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionRunJob {
    /// the action run job id
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// the action run job name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// the action run job needed ids
    #[serde(rename = "needs", skip_serializing_if = "Option::is_none")]
    pub needs: Option<Vec<String>>,
    /// the owner id
    #[serde(rename = "owner_id", skip_serializing_if = "Option::is_none")]
    pub owner_id: Option<i64>,
    /// the repository id
    #[serde(rename = "repo_id", skip_serializing_if = "Option::is_none")]
    pub repo_id: Option<i64>,
    /// the action run job labels to run on
    #[serde(rename = "runs_on", skip_serializing_if = "Option::is_none")]
    pub runs_on: Option<Vec<String>>,
    /// the action run job status
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// the action run job latest task id
    #[serde(rename = "task_id", skip_serializing_if = "Option::is_none")]
    pub task_id: Option<i64>,
}

impl ActionRunJob {
    /// ActionRunJob represents a job of a run
    pub fn new() -> ActionRunJob {
        ActionRunJob {
            id: None,
            name: None,
            needs: None,
            owner_id: None,
            repo_id: None,
            runs_on: None,
            status: None,
            task_id: None,
        }
    }
}
