/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionTaskResponse : ActionTaskResponse returns a ActionTask
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionTaskResponse {
    #[serde(rename = "total_count", skip_serializing_if = "Option::is_none")]
    pub total_count: Option<i64>,
    #[serde(rename = "workflow_runs", skip_serializing_if = "Option::is_none")]
    pub workflow_runs: Option<Vec<models::ActionTask>>,
}

impl ActionTaskResponse {
    /// ActionTaskResponse returns a ActionTask
    pub fn new() -> ActionTaskResponse {
        ActionTaskResponse {
            total_count: None,
            workflow_runs: None,
        }
    }
}

