/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionRun : ActionRun represents an action run
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionRun {
    /// the cron id for the schedule trigger
    #[serde(rename = "ScheduleID", skip_serializing_if = "Option::is_none")]
    pub schedule_id: Option<i64>,
    /// who approved this action run
    #[serde(rename = "approved_by", skip_serializing_if = "Option::is_none")]
    pub approved_by: Option<i64>,
    /// the commit sha the action run ran on
    #[serde(rename = "commit_sha", skip_serializing_if = "Option::is_none")]
    pub commit_sha: Option<String>,
    /// when the action run was created
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    /// A Duration represents the elapsed time between two instants as an int64 nanosecond count. The representation limits the largest representable duration to approximately 290 years.
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<i64>,
    /// the webhook event that causes the workflow to run
    #[serde(rename = "event", skip_serializing_if = "Option::is_none")]
    pub event: Option<String>,
    /// the payload of the webhook event that causes the workflow to run
    #[serde(rename = "event_payload", skip_serializing_if = "Option::is_none")]
    pub event_payload: Option<String>,
    /// the url of this action run
    #[serde(rename = "html_url", skip_serializing_if = "Option::is_none")]
    pub html_url: Option<String>,
    /// the action run id
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// a unique number for each run of a repository
    #[serde(rename = "index_in_repo", skip_serializing_if = "Option::is_none")]
    pub index_in_repo: Option<i64>,
    /// If this is triggered by a PR from a forked repository or an untrusted user, we need to check if it is approved and limit permissions when running the workflow.
    #[serde(
        rename = "is_fork_pull_request",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_fork_pull_request: Option<bool>,
    /// has the commit/tag/… the action run ran on been deleted
    #[serde(rename = "is_ref_deleted", skip_serializing_if = "Option::is_none")]
    pub is_ref_deleted: Option<bool>,
    /// may need approval if it's a fork pull request
    #[serde(rename = "need_approval", skip_serializing_if = "Option::is_none")]
    pub need_approval: Option<bool>,
    /// the commit/tag/… the action run ran on
    #[serde(rename = "prettyref", skip_serializing_if = "Option::is_none")]
    pub prettyref: Option<String>,
    #[serde(rename = "repository", skip_serializing_if = "Option::is_none")]
    pub repository: Option<Box<models::Repository>>,
    /// when the action run was started
    #[serde(rename = "started", skip_serializing_if = "Option::is_none")]
    pub started: Option<String>,
    /// the current status of this run
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// when the action run was stopped
    #[serde(rename = "stopped", skip_serializing_if = "Option::is_none")]
    pub stopped: Option<String>,
    /// the action run's title
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// the trigger event defined in the `on` configuration of the triggered workflow
    #[serde(rename = "trigger_event", skip_serializing_if = "Option::is_none")]
    pub trigger_event: Option<String>,
    #[serde(rename = "trigger_user", skip_serializing_if = "Option::is_none")]
    pub trigger_user: Option<Box<models::User>>,
    /// when the action run was last updated
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<String>,
    /// the name of workflow file
    #[serde(rename = "workflow_id", skip_serializing_if = "Option::is_none")]
    pub workflow_id: Option<String>,
}

impl ActionRun {
    /// ActionRun represents an action run
    pub fn new() -> ActionRun {
        ActionRun {
            schedule_id: None,
            approved_by: None,
            commit_sha: None,
            created: None,
            duration: None,
            event: None,
            event_payload: None,
            html_url: None,
            id: None,
            index_in_repo: None,
            is_fork_pull_request: None,
            is_ref_deleted: None,
            need_approval: None,
            prettyref: None,
            repository: None,
            started: None,
            status: None,
            stopped: None,
            title: None,
            trigger_event: None,
            trigger_user: None,
            updated: None,
            workflow_id: None,
        }
    }
}
