/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActivityPub : ActivityPub type
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivityPub {
    #[serde(rename = "@context", skip_serializing_if = "Option::is_none")]
    pub at_context: Option<String>,
}

impl ActivityPub {
    /// ActivityPub type
    pub fn new() -> ActivityPub {
        ActivityPub { at_context: None }
    }
}
