/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionTask : ActionTask represents a ActionTask
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionTask {
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "display_title", skip_serializing_if = "Option::is_none")]
    pub display_title: Option<String>,
    #[serde(rename = "event", skip_serializing_if = "Option::is_none")]
    pub event: Option<String>,
    #[serde(rename = "head_branch", skip_serializing_if = "Option::is_none")]
    pub head_branch: Option<String>,
    #[serde(rename = "head_sha", skip_serializing_if = "Option::is_none")]
    pub head_sha: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "run_number", skip_serializing_if = "Option::is_none")]
    pub run_number: Option<i64>,
    #[serde(rename = "run_started_at", skip_serializing_if = "Option::is_none")]
    pub run_started_at: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "workflow_id", skip_serializing_if = "Option::is_none")]
    pub workflow_id: Option<String>,
}

impl ActionTask {
    /// ActionTask represents a ActionTask
    pub fn new() -> ActionTask {
        ActionTask {
            created_at: None,
            display_title: None,
            event: None,
            head_branch: None,
            head_sha: None,
            id: None,
            name: None,
            run_number: None,
            run_started_at: None,
            status: None,
            updated_at: None,
            url: None,
            workflow_id: None,
        }
    }
}

