/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AddTimeOption : AddTimeOption options for adding time to an issue
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddTimeOption {
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    /// time in seconds
    #[serde(rename = "time")]
    pub time: i64,
    /// User who spent the time (optional)
    #[serde(rename = "user_name", skip_serializing_if = "Option::is_none")]
    pub user_name: Option<String>,
}

impl AddTimeOption {
    /// AddTimeOption options for adding time to an issue
    pub fn new(time: i64) -> AddTimeOption {
        AddTimeOption {
            created: None,
            time,
            user_name: None,
        }
    }
}

