/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AddCollaboratorOption : AddCollaboratorOption options when adding a user as a collaborator of a repository
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddCollaboratorOption {
    #[serde(rename = "permission", skip_serializing_if = "Option::is_none")]
    pub permission: Option<Permission>,
}

impl AddCollaboratorOption {
    /// AddCollaboratorOption options when adding a user as a collaborator of a repository
    pub fn new() -> AddCollaboratorOption {
        AddCollaboratorOption { permission: None }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Permission {
    #[serde(rename = "read")]
    Read,
    #[serde(rename = "write")]
    Write,
    #[serde(rename = "admin")]
    Admin,
}

impl Default for Permission {
    fn default() -> Permission {
        Self::Read
    }
}
