/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AnnotatedTagObject : AnnotatedTagObject contains meta information of the tag object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnnotatedTagObject {
    #[serde(rename = "sha", skip_serializing_if = "Option::is_none")]
    pub sha: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl AnnotatedTagObject {
    /// AnnotatedTagObject contains meta information of the tag object
    pub fn new() -> AnnotatedTagObject {
        AnnotatedTagObject {
            sha: None,
            r#type: None,
            url: None,
        }
    }
}

