/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiInvalidTopicsError {
    #[serde(rename = "invalidTopics", skip_serializing_if = "Option::is_none")]
    pub invalid_topics: Option<Vec<String>>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl ApiInvalidTopicsError {
    pub fn new() -> ApiInvalidTopicsError {
        ApiInvalidTopicsError {
            invalid_topics: None,
            message: None,
        }
    }
}
