/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockedUser {
    #[serde(rename = "block_id", skip_serializing_if = "Option::is_none")]
    pub block_id: Option<i64>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
}

impl BlockedUser {
    pub fn new() -> BlockedUser {
        BlockedUser {
            block_id: None,
            created_at: None,
        }
    }
}

