/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CommitStats : CommitStats is statistics for a RepoCommit
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommitStats {
    #[serde(rename = "additions", skip_serializing_if = "Option::is_none")]
    pub additions: Option<i64>,
    #[serde(rename = "deletions", skip_serializing_if = "Option::is_none")]
    pub deletions: Option<i64>,
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i64>,
}

impl CommitStats {
    /// CommitStats is statistics for a RepoCommit
    pub fn new() -> CommitStats {
        CommitStats {
            additions: None,
            deletions: None,
            total: None,
        }
    }
}
