/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Compare {
    #[serde(rename = "commits", skip_serializing_if = "Option::is_none")]
    pub commits: Option<Vec<models::Commit>>,
    #[serde(rename = "files", skip_serializing_if = "Option::is_none")]
    pub files: Option<Vec<models::CommitAffectedFiles>>,
    #[serde(rename = "total_commits", skip_serializing_if = "Option::is_none")]
    pub total_commits: Option<i64>,
}

impl Compare {
    pub fn new() -> Compare {
        Compare {
            commits: None,
            files: None,
            total_commits: None,
        }
    }
}

