/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateIssueCommentOption : CreateIssueCommentOption options for creating a comment on an issue
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateIssueCommentOption {
    #[serde(rename = "body")]
    pub body: String,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl CreateIssueCommentOption {
    /// CreateIssueCommentOption options for creating a comment on an issue
    pub fn new(body: String) -> CreateIssueCommentOption {
        CreateIssueCommentOption {
            body,
            updated_at: None,
        }
    }
}
