/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateHookOption : CreateHookOption options when create a hook
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateHookOption {
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(
        rename = "authorization_header",
        skip_serializing_if = "Option::is_none"
    )]
    pub authorization_header: Option<String>,
    #[serde(rename = "branch_filter", skip_serializing_if = "Option::is_none")]
    pub branch_filter: Option<String>,
    /// CreateHookOptionConfig has all config options in it required are \"content_type\" and \"url\" Required
    #[serde(rename = "config")]
    pub config: std::collections::HashMap<String, String>,
    #[serde(rename = "events", skip_serializing_if = "Option::is_none")]
    pub events: Option<Vec<String>>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl CreateHookOption {
    /// CreateHookOption options when create a hook
    pub fn new(
        config: std::collections::HashMap<String, String>,
        r#type: Type,
    ) -> CreateHookOption {
        CreateHookOption {
            active: None,
            authorization_header: None,
            branch_filter: None,
            config,
            events: None,
            r#type,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "forgejo")]
    Forgejo,
    #[serde(rename = "dingtalk")]
    Dingtalk,
    #[serde(rename = "discord")]
    Discord,
    #[serde(rename = "gitea")]
    Gitea,
    #[serde(rename = "gogs")]
    Gogs,
    #[serde(rename = "msteams")]
    Msteams,
    #[serde(rename = "slack")]
    Slack,
    #[serde(rename = "telegram")]
    Telegram,
    #[serde(rename = "feishu")]
    Feishu,
    #[serde(rename = "wechatwork")]
    Wechatwork,
    #[serde(rename = "packagist")]
    Packagist,
}

impl Default for Type {
    fn default() -> Type {
        Self::Forgejo
    }
}
