/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateQuotaRuleOptions : CreateQuotaRuleOptions represents the options for creating a quota rule
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateQuotaRuleOptions {
    /// The limit set by the rule
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    /// Name of the rule to create
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The subjects affected by the rule
    #[serde(rename = "subjects", skip_serializing_if = "Option::is_none")]
    pub subjects: Option<Vec<String>>,
}

impl CreateQuotaRuleOptions {
    /// CreateQuotaRuleOptions represents the options for creating a quota rule
    pub fn new() -> CreateQuotaRuleOptions {
        CreateQuotaRuleOptions {
            limit: None,
            name: None,
            subjects: None,
        }
    }
}

