/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateReleaseOption : CreateReleaseOption options when creating a release
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateReleaseOption {
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    #[serde(rename = "draft", skip_serializing_if = "Option::is_none")]
    pub draft: Option<bool>,
    #[serde(rename = "hide_archive_links", skip_serializing_if = "Option::is_none")]
    pub hide_archive_links: Option<bool>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "prerelease", skip_serializing_if = "Option::is_none")]
    pub prerelease: Option<bool>,
    #[serde(rename = "tag_name")]
    pub tag_name: String,
    #[serde(rename = "target_commitish", skip_serializing_if = "Option::is_none")]
    pub target_commitish: Option<String>,
}

impl CreateReleaseOption {
    /// CreateReleaseOption options when creating a release
    pub fn new(tag_name: String) -> CreateReleaseOption {
        CreateReleaseOption {
            body: None,
            draft: None,
            hide_archive_links: None,
            name: None,
            prerelease: None,
            tag_name,
            target_commitish: None,
        }
    }
}

