/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePushMirrorOption {
    #[serde(rename = "branch_filter", skip_serializing_if = "Option::is_none")]
    pub branch_filter: Option<String>,
    #[serde(rename = "interval", skip_serializing_if = "Option::is_none")]
    pub interval: Option<String>,
    #[serde(rename = "remote_address", skip_serializing_if = "Option::is_none")]
    pub remote_address: Option<String>,
    #[serde(rename = "remote_password", skip_serializing_if = "Option::is_none")]
    pub remote_password: Option<String>,
    #[serde(rename = "remote_username", skip_serializing_if = "Option::is_none")]
    pub remote_username: Option<String>,
    #[serde(rename = "sync_on_commit", skip_serializing_if = "Option::is_none")]
    pub sync_on_commit: Option<bool>,
    #[serde(rename = "use_ssh", skip_serializing_if = "Option::is_none")]
    pub use_ssh: Option<bool>,
}

impl CreatePushMirrorOption {
    pub fn new() -> CreatePushMirrorOption {
        CreatePushMirrorOption {
            branch_filter: None,
            interval: None,
            remote_address: None,
            remote_password: None,
            remote_username: None,
            sync_on_commit: None,
            use_ssh: None,
        }
    }
}
