/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateOrUpdateSecretOption : CreateOrUpdateSecretOption options when creating or updating secret
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateOrUpdateSecretOption {
    /// Data of the secret to update
    #[serde(rename = "data")]
    pub data: String,
}

impl CreateOrUpdateSecretOption {
    /// CreateOrUpdateSecretOption options when creating or updating secret
    pub fn new(data: String) -> CreateOrUpdateSecretOption {
        CreateOrUpdateSecretOption { data }
    }
}
