/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateOAuth2ApplicationOptions : CreateOAuth2ApplicationOptions holds options to create an oauth2 application
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateOAuth2ApplicationOptions {
    #[serde(rename = "confidential_client", skip_serializing_if = "Option::is_none")]
    pub confidential_client: Option<bool>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "redirect_uris", skip_serializing_if = "Option::is_none")]
    pub redirect_uris: Option<Vec<String>>,
}

impl CreateOAuth2ApplicationOptions {
    /// CreateOAuth2ApplicationOptions holds options to create an oauth2 application
    pub fn new() -> CreateOAuth2ApplicationOptions {
        CreateOAuth2ApplicationOptions {
            confidential_client: None,
            name: None,
            redirect_uris: None,
        }
    }
}

