/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateVariableOption : CreateVariableOption the option when creating variable
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateVariableOption {
    /// Value of the variable to create
    #[serde(rename = "value")]
    pub value: String,
}

impl CreateVariableOption {
    /// CreateVariableOption the option when creating variable
    pub fn new(value: String) -> CreateVariableOption {
        CreateVariableOption { value }
    }
}
