/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateQuotaGroupOptions : CreateQutaGroupOptions represents the options for creating a quota group
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateQuotaGroupOptions {
    /// Name of the quota group to create
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Rules to add to the newly created group. If a rule does not exist, it will be created.
    #[serde(rename = "rules", skip_serializing_if = "Option::is_none")]
    pub rules: Option<Vec<models::CreateQuotaRuleOptions>>,
}

impl CreateQuotaGroupOptions {
    /// CreateQutaGroupOptions represents the options for creating a quota group
    pub fn new() -> CreateQuotaGroupOptions {
        CreateQuotaGroupOptions {
            name: None,
            rules: None,
        }
    }
}

