/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeleteEmailOption : DeleteEmailOption options when deleting email addresses
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteEmailOption {
    /// email addresses to delete
    #[serde(rename = "emails", skip_serializing_if = "Option::is_none")]
    pub emails: Option<Vec<String>>,
}

impl DeleteEmailOption {
    /// DeleteEmailOption options when deleting email addresses
    pub fn new() -> DeleteEmailOption {
        DeleteEmailOption { emails: None }
    }
}
