/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeleteLabelsOption : DeleteLabelOption options for deleting a label
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteLabelsOption {
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl DeleteLabelsOption {
    /// DeleteLabelOption options for deleting a label
    pub fn new() -> DeleteLabelsOption {
        DeleteLabelsOption {
            updated_at: None,
        }
    }
}

