/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DismissPullReviewOptions : DismissPullReviewOptions are options to dismiss a pull review
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DismissPullReviewOptions {
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "priors", skip_serializing_if = "Option::is_none")]
    pub priors: Option<bool>,
}

impl DismissPullReviewOptions {
    /// DismissPullReviewOptions are options to dismiss a pull review
    pub fn new() -> DismissPullReviewOptions {
        DismissPullReviewOptions {
            message: None,
            priors: None,
        }
    }
}

