/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DispatchWorkflowRun : DispatchWorkflowRun represents a workflow run
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DispatchWorkflowRun {
    /// the workflow run id
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// the jobs name
    #[serde(rename = "jobs", skip_serializing_if = "Option::is_none")]
    pub jobs: Option<Vec<String>>,
    /// a unique number for each run of a repository
    #[serde(rename = "run_number", skip_serializing_if = "Option::is_none")]
    pub run_number: Option<i64>,
}

impl DispatchWorkflowRun {
    /// DispatchWorkflowRun represents a workflow run
    pub fn new() -> DispatchWorkflowRun {
        DispatchWorkflowRun {
            id: None,
            jobs: None,
            run_number: None,
        }
    }
}
