/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DispatchWorkflowOption : DispatchWorkflowOption options when dispatching a workflow
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DispatchWorkflowOption {
    /// Input keys and values configured in the workflow file.
    #[serde(rename = "inputs", skip_serializing_if = "Option::is_none")]
    pub inputs: Option<std::collections::HashMap<String, String>>,
    /// Git reference for the workflow
    #[serde(rename = "ref")]
    pub r#ref: String,
    /// Flag to return the run info
    #[serde(rename = "return_run_info", skip_serializing_if = "Option::is_none")]
    pub return_run_info: Option<bool>,
}

impl DispatchWorkflowOption {
    /// DispatchWorkflowOption options when dispatching a workflow
    pub fn new(r#ref: String) -> DispatchWorkflowOption {
        DispatchWorkflowOption {
            inputs: None,
            r#ref,
            return_run_info: None,
        }
    }
}

