/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EditAttachmentOptions : EditAttachmentOptions options for editing attachments
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditAttachmentOptions {
    /// (Can only be set if existing attachment is of external type)
    #[serde(rename = "browser_download_url", skip_serializing_if = "Option::is_none")]
    pub browser_download_url: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl EditAttachmentOptions {
    /// EditAttachmentOptions options for editing attachments
    pub fn new() -> EditAttachmentOptions {
        EditAttachmentOptions {
            browser_download_url: None,
            name: None,
        }
    }
}

