/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EditDeadlineOption : EditDeadlineOption options for creating a deadline
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditDeadlineOption {
    #[serde(rename = "due_date")]
    pub due_date: String,
}

impl EditDeadlineOption {
    /// EditDeadlineOption options for creating a deadline
    pub fn new(due_date: String) -> EditDeadlineOption {
        EditDeadlineOption {
            due_date,
        }
    }
}

