/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EditQuotaRuleOptions : EditQuotaRuleOptions represents the options for editing a quota rule
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditQuotaRuleOptions {
    /// The limit set by the rule
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    /// The subjects affected by the rule
    #[serde(rename = "subjects", skip_serializing_if = "Option::is_none")]
    pub subjects: Option<Vec<String>>,
}

impl EditQuotaRuleOptions {
    /// EditQuotaRuleOptions represents the options for editing a quota rule
    pub fn new() -> EditQuotaRuleOptions {
        EditQuotaRuleOptions {
            limit: None,
            subjects: None,
        }
    }
}
