/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ExternalWiki : ExternalWiki represents setting for external wiki
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExternalWiki {
    /// URL of external wiki.
    #[serde(rename = "external_wiki_url", skip_serializing_if = "Option::is_none")]
    pub external_wiki_url: Option<String>,
}

impl ExternalWiki {
    /// ExternalWiki represents setting for external wiki
    pub fn new() -> ExternalWiki {
        ExternalWiki {
            external_wiki_url: None,
        }
    }
}
