/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FileResponse : FileResponse contains information about a repo's file
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileResponse {
    #[serde(rename = "commit", skip_serializing_if = "Option::is_none")]
    pub commit: Option<Box<models::FileCommitResponse>>,
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<Box<models::ContentsResponse>>,
    #[serde(rename = "verification", skip_serializing_if = "Option::is_none")]
    pub verification: Option<Box<models::PayloadCommitVerification>>,
}

impl FileResponse {
    /// FileResponse contains information about a repo's file
    pub fn new() -> FileResponse {
        FileResponse {
            commit: None,
            content: None,
            verification: None,
        }
    }
}

