/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GpgKeyEmail : GPGKeyEmail an email attached to a GPGKey
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GpgKeyEmail {
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "verified", skip_serializing_if = "Option::is_none")]
    pub verified: Option<bool>,
}

impl GpgKeyEmail {
    /// GPGKeyEmail an email attached to a GPGKey
    pub fn new() -> GpgKeyEmail {
        GpgKeyEmail {
            email: None,
            verified: None,
        }
    }
}
