/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueConfig {
    #[serde(
        rename = "blank_issues_enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub blank_issues_enabled: Option<bool>,
    #[serde(rename = "contact_links", skip_serializing_if = "Option::is_none")]
    pub contact_links: Option<Vec<models::IssueConfigContactLink>>,
}

impl IssueConfig {
    pub fn new() -> IssueConfig {
        IssueConfig {
            blank_issues_enabled: None,
            contact_links: None,
        }
    }
}
