/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IssueDeadline : IssueDeadline represents an issue deadline
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueDeadline {
    #[serde(rename = "due_date", skip_serializing_if = "Option::is_none")]
    pub due_date: Option<String>,
}

impl IssueDeadline {
    /// IssueDeadline represents an issue deadline
    pub fn new() -> IssueDeadline {
        IssueDeadline { due_date: None }
    }
}
