/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IssueLabelsOption : IssueLabelsOption a collection of labels
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueLabelsOption {
    /// Labels can be a list of integers representing label IDs or a list of strings representing label names
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<Vec<serde_json::Value>>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl IssueLabelsOption {
    /// IssueLabelsOption a collection of labels
    pub fn new() -> IssueLabelsOption {
        IssueLabelsOption {
            labels: None,
            updated_at: None,
        }
    }
}
