/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LabelTemplate : LabelTemplate info of a Label template
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LabelTemplate {
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "exclusive", skip_serializing_if = "Option::is_none")]
    pub exclusive: Option<bool>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl LabelTemplate {
    /// LabelTemplate info of a Label template
    pub fn new() -> LabelTemplate {
        LabelTemplate {
            color: None,
            description: None,
            exclusive: None,
            name: None,
        }
    }
}

