/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NewIssuePinsAllowed : NewIssuePinsAllowed represents an API response that says if new Issue Pins are allowed
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewIssuePinsAllowed {
    #[serde(rename = "issues", skip_serializing_if = "Option::is_none")]
    pub issues: Option<bool>,
    #[serde(rename = "pull_requests", skip_serializing_if = "Option::is_none")]
    pub pull_requests: Option<bool>,
}

impl NewIssuePinsAllowed {
    /// NewIssuePinsAllowed represents an API response that says if new Issue Pins are allowed
    pub fn new() -> NewIssuePinsAllowed {
        NewIssuePinsAllowed {
            issues: None,
            pull_requests: None,
        }
    }
}

