/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Note : Note contains information related to a git note
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Note {
    #[serde(rename = "commit", skip_serializing_if = "Option::is_none")]
    pub commit: Option<Box<models::Commit>>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl Note {
    /// Note contains information related to a git note
    pub fn new() -> Note {
        Note {
            commit: None,
            message: None,
        }
    }
}

