/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NotificationCount : NotificationCount number of unread notifications
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationCount {
    #[serde(rename = "new", skip_serializing_if = "Option::is_none")]
    pub new: Option<i64>,
}

impl NotificationCount {
    /// NotificationCount number of unread notifications
    pub fn new() -> NotificationCount {
        NotificationCount {
            new: None,
        }
    }
}

