/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PayloadUser : PayloadUser represents the author or committer of a commit
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PayloadUser {
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// Full name of the commit author
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

impl PayloadUser {
    /// PayloadUser represents the author or committer of a commit
    pub fn new() -> PayloadUser {
        PayloadUser {
            email: None,
            name: None,
            username: None,
        }
    }
}

