/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PullReviewRequestOptions : PullReviewRequestOptions are options to add or remove pull review requests
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PullReviewRequestOptions {
    #[serde(rename = "reviewers", skip_serializing_if = "Option::is_none")]
    pub reviewers: Option<Vec<String>>,
    #[serde(rename = "team_reviewers", skip_serializing_if = "Option::is_none")]
    pub team_reviewers: Option<Vec<String>>,
}

impl PullReviewRequestOptions {
    /// PullReviewRequestOptions are options to add or remove pull review requests
    pub fn new() -> PullReviewRequestOptions {
        PullReviewRequestOptions {
            reviewers: None,
            team_reviewers: None,
        }
    }
}

