/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QuotaGroup : QuotaGroup represents a quota group
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuotaGroup {
    /// Name of the group
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Rules associated with the group
    #[serde(rename = "rules", skip_serializing_if = "Option::is_none")]
    pub rules: Option<Vec<models::QuotaRuleInfo>>,
}

impl QuotaGroup {
    /// QuotaGroup represents a quota group
    pub fn new() -> QuotaGroup {
        QuotaGroup {
            name: None,
            rules: None,
        }
    }
}

