/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QuotaUsedAttachment : QuotaUsedAttachment represents an attachment counting towards a user's quota
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuotaUsedAttachment {
    /// API URL for the attachment
    #[serde(rename = "api_url", skip_serializing_if = "Option::is_none")]
    pub api_url: Option<String>,
    #[serde(rename = "contained_in", skip_serializing_if = "Option::is_none")]
    pub contained_in: Option<Box<models::QuotaUsedAttachmentContainedIn>>,
    /// Filename of the attachment
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Size of the attachment (in bytes)
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i64>,
}

impl QuotaUsedAttachment {
    /// QuotaUsedAttachment represents an attachment counting towards a user's quota
    pub fn new() -> QuotaUsedAttachment {
        QuotaUsedAttachment {
            api_url: None,
            contained_in: None,
            name: None,
            size: None,
        }
    }
}

