/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QuotaUsedSize : QuotaUsedSize represents the size-based quota usage of a user
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuotaUsedSize {
    #[serde(rename = "assets", skip_serializing_if = "Option::is_none")]
    pub assets: Option<Box<models::QuotaUsedSizeAssets>>,
    #[serde(rename = "git", skip_serializing_if = "Option::is_none")]
    pub git: Option<Box<models::QuotaUsedSizeGit>>,
    #[serde(rename = "repos", skip_serializing_if = "Option::is_none")]
    pub repos: Option<Box<models::QuotaUsedSizeRepos>>,
}

impl QuotaUsedSize {
    /// QuotaUsedSize represents the size-based quota usage of a user
    pub fn new() -> QuotaUsedSize {
        QuotaUsedSize {
            assets: None,
            git: None,
            repos: None,
        }
    }
}

