/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QuotaUsedArtifact : QuotaUsedArtifact represents an artifact counting towards a user's quota
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuotaUsedArtifact {
    /// HTML URL to the action run containing the artifact
    #[serde(rename = "html_url", skip_serializing_if = "Option::is_none")]
    pub html_url: Option<String>,
    /// Name of the artifact
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Size of the artifact (compressed)
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i64>,
}

impl QuotaUsedArtifact {
    /// QuotaUsedArtifact represents an artifact counting towards a user's quota
    pub fn new() -> QuotaUsedArtifact {
        QuotaUsedArtifact {
            html_url: None,
            name: None,
            size: None,
        }
    }
}

