/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QuotaUsedSizeAssets : QuotaUsedSizeAssets represents the size-based asset usage of a user
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuotaUsedSizeAssets {
    /// Storage size used for the user's artifacts
    #[serde(rename = "artifacts", skip_serializing_if = "Option::is_none")]
    pub artifacts: Option<i64>,
    #[serde(rename = "attachments", skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Box<models::QuotaUsedSizeAssetsAttachments>>,
    #[serde(rename = "packages", skip_serializing_if = "Option::is_none")]
    pub packages: Option<Box<models::QuotaUsedSizeAssetsPackages>>,
}

impl QuotaUsedSizeAssets {
    /// QuotaUsedSizeAssets represents the size-based asset usage of a user
    pub fn new() -> QuotaUsedSizeAssets {
        QuotaUsedSizeAssets {
            artifacts: None,
            attachments: None,
            packages: None,
        }
    }
}

