/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QuotaUsed : QuotaUsed represents the quota usage of a user
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuotaUsed {
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<Box<models::QuotaUsedSize>>,
}

impl QuotaUsed {
    /// QuotaUsed represents the quota usage of a user
    pub fn new() -> QuotaUsed {
        QuotaUsed { size: None }
    }
}
