/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QuotaUsedSizeRepos : QuotaUsedSizeRepos represents the size-based repository quota usage of a user
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuotaUsedSizeRepos {
    /// Storage size of the user's private repositories
    #[serde(rename = "private", skip_serializing_if = "Option::is_none")]
    pub private: Option<i64>,
    /// Storage size of the user's public repositories
    #[serde(rename = "public", skip_serializing_if = "Option::is_none")]
    pub public: Option<i64>,
}

impl QuotaUsedSizeRepos {
    /// QuotaUsedSizeRepos represents the size-based repository quota usage of a user
    pub fn new() -> QuotaUsedSizeRepos {
        QuotaUsedSizeRepos {
            private: None,
            public: None,
        }
    }
}

