/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QuotaRuleInfo : QuotaRuleInfo contains information about a quota rule
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuotaRuleInfo {
    /// The limit set by the rule
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    /// Name of the rule (only shown to admins)
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Subjects the rule affects
    #[serde(rename = "subjects", skip_serializing_if = "Option::is_none")]
    pub subjects: Option<Vec<String>>,
}

impl QuotaRuleInfo {
    /// QuotaRuleInfo contains information about a quota rule
    pub fn new() -> QuotaRuleInfo {
        QuotaRuleInfo {
            limit: None,
            name: None,
            subjects: None,
        }
    }
}

