/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QuotaUsedSizeAssetsAttachments : QuotaUsedSizeAssetsAttachments represents the size-based attachment quota usage of a user
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuotaUsedSizeAssetsAttachments {
    /// Storage size used for the user's issue & comment attachments
    #[serde(rename = "issues", skip_serializing_if = "Option::is_none")]
    pub issues: Option<i64>,
    /// Storage size used for the user's release attachments
    #[serde(rename = "releases", skip_serializing_if = "Option::is_none")]
    pub releases: Option<i64>,
}

impl QuotaUsedSizeAssetsAttachments {
    /// QuotaUsedSizeAssetsAttachments represents the size-based attachment quota usage of a user
    pub fn new() -> QuotaUsedSizeAssetsAttachments {
        QuotaUsedSizeAssetsAttachments {
            issues: None,
            releases: None,
        }
    }
}

