/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QuotaInfo : QuotaInfo represents information about a user's quota
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuotaInfo {
    /// QuotaGroupList represents a list of quota groups
    #[serde(rename = "groups", skip_serializing_if = "Option::is_none")]
    pub groups: Option<Vec<models::QuotaGroup>>,
    #[serde(rename = "used", skip_serializing_if = "Option::is_none")]
    pub used: Option<Box<models::QuotaUsed>>,
}

impl QuotaInfo {
    /// QuotaInfo represents information about a user's quota
    pub fn new() -> QuotaInfo {
        QuotaInfo {
            groups: None,
            used: None,
        }
    }
}

