/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QuotaUsedAttachmentContainedIn : Context for the attachment: URLs to the containing object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuotaUsedAttachmentContainedIn {
    /// API URL for the object that contains this attachment
    #[serde(rename = "api_url", skip_serializing_if = "Option::is_none")]
    pub api_url: Option<String>,
    /// HTML URL for the object that contains this attachment
    #[serde(rename = "html_url", skip_serializing_if = "Option::is_none")]
    pub html_url: Option<String>,
}

impl QuotaUsedAttachmentContainedIn {
    /// Context for the attachment: URLs to the containing object
    pub fn new() -> QuotaUsedAttachmentContainedIn {
        QuotaUsedAttachmentContainedIn {
            api_url: None,
            html_url: None,
        }
    }
}

