/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RegistrationToken : RegistrationToken is a string used to register a runner with a server
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegistrationToken {
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
}

impl RegistrationToken {
    /// RegistrationToken is a string used to register a runner with a server
    pub fn new() -> RegistrationToken {
        RegistrationToken { token: None }
    }
}
