/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RenameUserOption : RenameUserOption options when renaming a user
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RenameUserOption {
    /// New username for this user. This name cannot be in use yet by any other user.
    #[serde(rename = "new_username")]
    pub new_username: String,
}

impl RenameUserOption {
    /// RenameUserOption options when renaming a user
    pub fn new(new_username: String) -> RenameUserOption {
        RenameUserOption { new_username }
    }
}
