/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReplaceFlagsOption : ReplaceFlagsOption options when replacing the flags of a repository
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReplaceFlagsOption {
    #[serde(rename = "flags", skip_serializing_if = "Option::is_none")]
    pub flags: Option<Vec<String>>,
}

impl ReplaceFlagsOption {
    /// ReplaceFlagsOption options when replacing the flags of a repository
    pub fn new() -> ReplaceFlagsOption {
        ReplaceFlagsOption {
            flags: None,
        }
    }
}

