/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RepoTopicOptions : RepoTopicOptions a collection of repo topic names
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RepoTopicOptions {
    /// list of topic names
    #[serde(rename = "topics", skip_serializing_if = "Option::is_none")]
    pub topics: Option<Vec<String>>,
}

impl RepoTopicOptions {
    /// RepoTopicOptions a collection of repo topic names
    pub fn new() -> RepoTopicOptions {
        RepoTopicOptions {
            topics: None,
        }
    }
}

