/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ServerVersion : ServerVersion wraps the version of the server
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerVersion {
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl ServerVersion {
    /// ServerVersion wraps the version of the server
    pub fn new() -> ServerVersion {
        ServerVersion { version: None }
    }
}
