/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SetUserQuotaGroupsOptions : SetUserQuotaGroupsOptions represents the quota groups of a user
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetUserQuotaGroupsOptions {
    /// Quota groups the user shall have
    #[serde(rename = "groups")]
    pub groups: Vec<String>,
}

impl SetUserQuotaGroupsOptions {
    /// SetUserQuotaGroupsOptions represents the quota groups of a user
    pub fn new(groups: Vec<String>) -> SetUserQuotaGroupsOptions {
        SetUserQuotaGroupsOptions {
            groups,
        }
    }
}

