/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SyncForkInfo : SyncForkInfo information about syncing a fork
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncForkInfo {
    #[serde(rename = "allowed", skip_serializing_if = "Option::is_none")]
    pub allowed: Option<bool>,
    #[serde(rename = "base_commit", skip_serializing_if = "Option::is_none")]
    pub base_commit: Option<String>,
    #[serde(rename = "commits_behind", skip_serializing_if = "Option::is_none")]
    pub commits_behind: Option<i64>,
    #[serde(rename = "fork_commit", skip_serializing_if = "Option::is_none")]
    pub fork_commit: Option<String>,
}

impl SyncForkInfo {
    /// SyncForkInfo information about syncing a fork
    pub fn new() -> SyncForkInfo {
        SyncForkInfo {
            allowed: None,
            base_commit: None,
            commits_behind: None,
            fork_commit: None,
        }
    }
}
