/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TagProtection : TagProtection represents a tag protection
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TagProtection {
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "name_pattern", skip_serializing_if = "Option::is_none")]
    pub name_pattern: Option<String>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "whitelist_teams", skip_serializing_if = "Option::is_none")]
    pub whitelist_teams: Option<Vec<String>>,
    #[serde(rename = "whitelist_usernames", skip_serializing_if = "Option::is_none")]
    pub whitelist_usernames: Option<Vec<String>>,
}

impl TagProtection {
    /// TagProtection represents a tag protection
    pub fn new() -> TagProtection {
        TagProtection {
            created_at: None,
            id: None,
            name_pattern: None,
            updated_at: None,
            whitelist_teams: None,
            whitelist_usernames: None,
        }
    }
}

