/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TagArchiveDownloadCount : TagArchiveDownloadCount counts how many times a archive was downloaded
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TagArchiveDownloadCount {
    #[serde(rename = "tar_gz", skip_serializing_if = "Option::is_none")]
    pub tar_gz: Option<i64>,
    #[serde(rename = "zip", skip_serializing_if = "Option::is_none")]
    pub zip: Option<i64>,
}

impl TagArchiveDownloadCount {
    /// TagArchiveDownloadCount counts how many times a archive was downloaded
    pub fn new() -> TagArchiveDownloadCount {
        TagArchiveDownloadCount {
            tar_gz: None,
            zip: None,
        }
    }
}

