/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TopicResponse : TopicResponse for returning topics
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TopicResponse {
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "repo_count", skip_serializing_if = "Option::is_none")]
    pub repo_count: Option<i64>,
    #[serde(rename = "topic_name", skip_serializing_if = "Option::is_none")]
    pub topic_name: Option<String>,
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<String>,
}

impl TopicResponse {
    /// TopicResponse for returning topics
    pub fn new() -> TopicResponse {
        TopicResponse {
            created: None,
            id: None,
            repo_count: None,
            topic_name: None,
            updated: None,
        }
    }
}

