/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TopicName : TopicName a list of repo topic names
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TopicName {
    #[serde(rename = "topics", skip_serializing_if = "Option::is_none")]
    pub topics: Option<Vec<String>>,
}

impl TopicName {
    /// TopicName a list of repo topic names
    pub fn new() -> TopicName {
        TopicName { topics: None }
    }
}
