/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateVariableOption : UpdateVariableOption the option when updating variable
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateVariableOption {
    /// New name for the variable. If the field is empty, the variable name won't be updated.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Value of the variable to update
    #[serde(rename = "value")]
    pub value: String,
}

impl UpdateVariableOption {
    /// UpdateVariableOption the option when updating variable
    pub fn new(value: String) -> UpdateVariableOption {
        UpdateVariableOption {
            name: None,
            value,
        }
    }
}

