/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateBranchRepoOption : UpdateBranchRepoOption options when updating a branch in a repository
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateBranchRepoOption {
    /// New branch name
    #[serde(rename = "name")]
    pub name: String,
}

impl UpdateBranchRepoOption {
    /// UpdateBranchRepoOption options when updating a branch in a repository
    pub fn new(name: String) -> UpdateBranchRepoOption {
        UpdateBranchRepoOption {
            name,
        }
    }
}

