/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateUserAvatarOption : UpdateUserAvatarUserOption options when updating the user avatar
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateUserAvatarOption {
    /// image must be base64 encoded
    #[serde(rename = "image", skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
}

impl UpdateUserAvatarOption {
    /// UpdateUserAvatarUserOption options when updating the user avatar
    pub fn new() -> UpdateUserAvatarOption {
        UpdateUserAvatarOption {
            image: None,
        }
    }
}

