/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserSettings : UserSettings represents user settings
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSettings {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "diff_view_style", skip_serializing_if = "Option::is_none")]
    pub diff_view_style: Option<String>,
    #[serde(rename = "enable_repo_unit_hints", skip_serializing_if = "Option::is_none")]
    pub enable_repo_unit_hints: Option<bool>,
    #[serde(rename = "full_name", skip_serializing_if = "Option::is_none")]
    pub full_name: Option<String>,
    #[serde(rename = "hide_activity", skip_serializing_if = "Option::is_none")]
    pub hide_activity: Option<bool>,
    /// Privacy
    #[serde(rename = "hide_email", skip_serializing_if = "Option::is_none")]
    pub hide_email: Option<bool>,
    #[serde(rename = "hide_pronouns", skip_serializing_if = "Option::is_none")]
    pub hide_pronouns: Option<bool>,
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    #[serde(rename = "pronouns", skip_serializing_if = "Option::is_none")]
    pub pronouns: Option<String>,
    #[serde(rename = "theme", skip_serializing_if = "Option::is_none")]
    pub theme: Option<String>,
    #[serde(rename = "website", skip_serializing_if = "Option::is_none")]
    pub website: Option<String>,
}

impl UserSettings {
    /// UserSettings represents user settings
    pub fn new() -> UserSettings {
        UserSettings {
            description: None,
            diff_view_style: None,
            enable_repo_unit_hints: None,
            full_name: None,
            hide_activity: None,
            hide_email: None,
            hide_pronouns: None,
            language: None,
            location: None,
            pronouns: None,
            theme: None,
            website: None,
        }
    }
}

