/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserHeatmapData : UserHeatmapData represents the data needed to create a heatmap
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserHeatmapData {
    #[serde(rename = "contributions", skip_serializing_if = "Option::is_none")]
    pub contributions: Option<i64>,
    /// TimeStamp defines a timestamp
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i64>,
}

impl UserHeatmapData {
    /// UserHeatmapData represents the data needed to create a heatmap
    pub fn new() -> UserHeatmapData {
        UserHeatmapData {
            contributions: None,
            timestamp: None,
        }
    }
}

