/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VerifyGpgKeyOption : VerifyGPGKeyOption options verifies user GPG key
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyGpgKeyOption {
    #[serde(rename = "armored_signature", skip_serializing_if = "Option::is_none")]
    pub armored_signature: Option<String>,
    /// An Signature for a GPG key token
    #[serde(rename = "key_id")]
    pub key_id: String,
}

impl VerifyGpgKeyOption {
    /// VerifyGPGKeyOption options verifies user GPG key
    pub fn new(key_id: String) -> VerifyGpgKeyOption {
        VerifyGpgKeyOption {
            armored_signature: None,
            key_id,
        }
    }
}

