/*
 * Forgejo API
 *
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 14.0.3+gitea-1.22.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WikiCommitList : WikiCommitList commit/revision list
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WikiCommitList {
    #[serde(rename = "commits", skip_serializing_if = "Option::is_none")]
    pub commits: Option<Vec<models::WikiCommit>>,
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
}

impl WikiCommitList {
    /// WikiCommitList commit/revision list
    pub fn new() -> WikiCommitList {
        WikiCommitList {
            commits: None,
            count: None,
        }
    }
}

